'use strict';
// Windows Chromium host. Remote content never receives a preload or Node/IPC APIs.
const {app,BrowserWindow,WebContentsView,ipcMain,session,dialog,shell,Menu,nativeTheme,Notification,safeStorage,net}=require('electron');
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
const {Store,id,safeString,webURL,originOf,navigateInput,searchURL,boundedRect,metadataTab,INTERNAL_PAGES}=require('./lib/core.cjs');
const {createVault}=require('./lib/vault.cjs');const {createCloud}=require('./lib/cloud.cjs');const {createBlocker}=require('./lib/adblock.cjs');
const APP_URL=pathToFileURL(path.join(__dirname,'renderer/index.html')).href;
let win,store,vault,cloud,browserSession,blocker;
let tabs=[],activeTabId=null,splitTabId=null,layout=null,quitting=false,closingWindow=false,syncTimer=null;
const liveDownloads=new Map();const reminderTimers=new Map();const closedTabs=[];
const assistant={visible:false,running:false,chatId:null,messages:[],status:'',error:null,attachments:[]};
let assistantGeneration=0;
let passwordMetadata=[],cloudState={configured:false},restoreTabs=[];
let config={};try{config=JSON.parse(fs.readFileSync(path.join(__dirname,'config.generated.json'),'utf8'));}catch{}
// Developers may supply existing configuration through the environment, never through the web UI.
config.aiBaseURL=process.env.BREEZE_CLOUD_AI_BASE_URL||config.aiBaseURL||'';
config.aiClientToken=process.env.BREEZE_CLOUD_CLIENT_TOKEN||config.aiClientToken||'';
config.supabaseURL=process.env.BREEZE_CLOUD_SUPABASE_URL||config.supabaseURL||'';
config.supabaseAnonKey=process.env.BREEZE_CLOUD_SUPABASE_ANON_KEY||config.supabaseAnonKey||'';
if(config.development)Object.assign(config,{aiBaseURL:'',aiClientToken:'',supabaseURL:'',supabaseAnonKey:''});
const profileArg=process.argv.find(a=>a.startsWith('--profile='));
if(profileArg){const name=profileArg.slice(10);if(/^[a-zA-Z0-9_-]{1,80}$/.test(name))app.setPath('userData',path.join(app.getPath('appData'),name));}
if(process.argv.includes('--smoke-test'))app.setPath('userData',fs.mkdtempSync(path.join(require('node:os').tmpdir(),'breeze-smoke-')));
app.setName(config.development?'Breeze Test':'Breeze');
if(process.platform==='win32')app.setAppUserModelId(config.development?'com.froydinger.breeze.windows.test':'com.froydinger.breeze.windows');
const gotLock=app.requestSingleInstanceLock();if(!gotLock)app.quit();
app.on('second-instance',(_event,argv)=>{if(win){if(win.isMinimized())win.restore();win.focus();}handleAuthURL(argv.find(a=>a.match(/^com\.froydinger\.breeze:/)));});
app.on('open-url',(event,url)=>{event.preventDefault();handleAuthURL(url);});
app.on('window-all-closed',()=>app.quit());
app.on('before-quit',()=>{quitting=true;for(const timer of reminderTimers.values())clearTimeout(timer);clearTimeout(syncTimer);cloud?.aero?.cancel();saveTabs();});
function getTab(tabId=activeTabId){return tabs.find(t=>t.id===tabId);}
function settings(){return store.get('settings');}
function event(data){if(win&&!win.isDestroyed())win.webContents.send('breeze:event',data);}
function snapshot(){const tab=getTab();return {version:app.getVersion(),development:!!config.development,buildLabel:config.development?'Unconfigured Windows test build':'Windows',platform:process.platform,chromiumVersion:process.versions.chrome,electronVersion:process.versions.electron,tabs:tabs.map(metadataTab),activeTabId,splitTabId,internalPage:tab?.page??null,pins:store.get('pins'),groups:store.get('groups'),settings:settings(),history:store.get('history'),bookmarks:store.get('bookmarks'),downloads:store.get('downloads'),chats:store.get('chats'),reminders:store.get('reminders'),cloud:{...cloudState,configured:!!cloudState.configured,aeroConfigured:!!(config.aiBaseURL&&config.aiClientToken),account:cloudState.signedIn?{...cloudState,email:cloudState.email}:null},passwords:passwordMetadata,assistant:{...assistant,attachments:assistant.attachments.map(({id,name})=>({id,name}))},restoreTabs,systemDark:nativeTheme.shouldUseDarkColors,maximized:win?.isMaximized()||false};}
function broadcast(){if(!win||win.isDestroyed())return;win.webContents.send('breeze:state',snapshot());}
function toast(text,type='info'){event({type:'toast',text,error:type==='error'});}
function saveTabs(){if(!store)return;const pending=restoreTabs.filter(r=>webURL(r.url));store.set('openTabs',[...pending,...tabs.filter(t=>webURL(t.url)).map(t=>({id:t.id,url:t.url,title:t.title,groupId:t.groupId||null,pinned:t.pinned||false,sleeping:t.sleeping||false}))].filter((t,i,all)=>all.findIndex(r=>r.url===t.url)===i));}
function changed(collection){broadcast();if(!cloud?.account?.isApplyingChanges?.()&&['history','pins','bookmarks','chats','reminders','openTabs','settings','passwords'].includes(collection)){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{cloud?.account?.syncNow().catch(()=>{});},2000);}}
function updateTab(tab,patch){Object.assign(tab,patch);broadcast();}
function applyTheme(){nativeTheme.themeSource=settings().theme;win?.setBackgroundColor(nativeTheme.shouldUseDarkColors?'#000000':'#ffffff');}
function positionViews(){if(!win||!layout)return;const bounds=win.getContentBounds();const active=getTab();for(const tab of tabs){if(!tab.view)continue;const visible=!layout.overlayOpen&&layout.width>0&&layout.height>0&&!active?.page&&(tab.id===activeTabId||tab.id===splitTabId);tab.view.setVisible(visible);if(visible){const rect=tab.id===splitTabId&&layout.split?layout.split:layout;tab.view.setBounds(boundedRect(rect,bounds));}}}
function createTab(value='breeze://newtab',{activate=true,split=false,groupId=null,pinned=false,deferred=false}={}){
  const dest=navigateInput(value,settings().searchEngine);const tab={id:id(),url:dest.url,page:dest.page,title:dest.page?'New Tab':dest.url,loading:false,canGoBack:false,canGoForward:false,pinned,groupId,muted:false,sleeping:false,lastActive:Date.now(),error:null};
  tabs.push(tab);if(activate&&!split){activeTabId=tab.id;splitTabId=null;}if(split){if(!activeTabId)activeTabId=tab.id;else splitTabId=tab.id;}
  if(!tab.page&&!deferred)createView(tab);positionViews();saveTabs();broadcast();return metadataTab(tab);
}
function hookKeys(contents){contents.on('before-input-event',(e,input)=>{if(input.type!=='keyDown')return;const ctrl=input.control||input.meta;let handled=true;const key=input.key.toLowerCase();if(ctrl&&key==='l'){win.webContents.focus();event({type:'focus-address'});}else if(ctrl&&key==='t'&&!input.shift){createTab();event({type:'focus-address'});}else if(ctrl&&key==='t'&&input.shift){const last=closedTabs.pop();if(last)createTab(last.url);}else if(ctrl&&key==='w'){closeTab(activeTabId);}else if(ctrl&&(key==='r'||key==='f5'))reloadTab();else if(key==='f5')reloadTab();else if(ctrl&&key==='f'){win.webContents.focus();event({type:'find-open'});}else if(ctrl&&key==='d'){try{bookmarkCurrent();}catch(error){toast(error.message);}}else if(ctrl&&key==='h')openInternal('history');else if(ctrl&&key==='j'&&input.shift)openInternal('downloads');else if(ctrl&&key==='j'){assistant.visible=!assistant.visible;broadcast();}else if(ctrl&&key==='p')getTab()?.view?.webContents.print();else if(ctrl&&key==='tab'){const i=tabs.findIndex(t=>t.id===activeTabId);activateTab(tabs[(i+(input.shift?-1:1)+tabs.length)%tabs.length]?.id);}else if(input.alt&&key==='arrowleft')goBack();else if(input.alt&&key==='arrowright')goForward();else if(ctrl&&['+','=','-','0'].includes(key))zoom(key);else if(key==='f11')win.setFullScreen(!win.isFullScreen());else if(key==='escape'){getTab()?.view?.webContents.stopFindInPage('clearSelection');event({type:'escape'});}else handled=false;if(handled)e.preventDefault();});}
function createView(tab,inheritedPreferences={},load=true){
  if(tab.view)return tab.view;
  const view=new WebContentsView({webPreferences:{...inheritedPreferences,preload:undefined,session:browserSession,contextIsolation:true,sandbox:true,nodeIntegration:false,nodeIntegrationInWorker:false,webSecurity:true,allowRunningInsecureContent:false,webviewTag:false,plugins:false,backgroundThrottling:true}});
  tab.view=view;tab.sleeping=false;win.contentView.addChildView(view);view.setVisible(false);const wc=view.webContents;
  // Preserve Chromium compatibility without pretending to be a different browser engine.
  wc.setUserAgent(wc.getUserAgent().replace(/\sElectron\/[^\s]+/,'').replace(/\sBreeze\/[^\s]+/,''));
  hookKeys(wc);
  const protect=(e,url)=>{const target=url||e.url;if(!webURL(target)&&target!=='about:blank'){e.preventDefault();if(/^https?:/i.test(target))return;toast('Breeze blocked a non-web navigation.');}};
  wc.on('will-navigate',protect);wc.on('will-redirect',protect);
  wc.on('will-attach-webview',e=>e.preventDefault());
  wc.setWindowOpenHandler(({url,disposition})=>{
    if((!webURL(url)&&url!=='about:blank')||blocker?.shouldBlock({url,resourceType:'mainFrame',isPopup:true,webContentsId:wc.id,referrer:wc.getURL()}))return{action:'deny'};
    return {action:'allow',outlivesOpener:true,createWindow:options=>{const created=createTab(url==='about:blank'?'breeze://newtab':url,{activate:disposition!=='background-tab',deferred:true});const child=getTab(created.id);child.url=url;child.page=null;child.title='New Tab';const childView=createView(child,options.webPreferences||{},false);positionViews();broadcast();return childView.webContents;}};
  });
  wc.on('did-start-loading',()=>updateTab(tab,{loading:true,error:null}));
  wc.on('did-stop-loading',()=>{if(wc.isDestroyed())return;updateTab(tab,{loading:false,canGoBack:wc.navigationHistory.canGoBack(),canGoForward:wc.navigationHistory.canGoForward()});});
  wc.on('did-navigate',(_e,url)=>{if(!webURL(url))return;tab.url=url;tab.page=null;tab.lastActive=Date.now();wc.setZoomFactor(1);recordHistory(tab);saveTabs();broadcast();});
  wc.on('did-navigate-in-page',(_e,url,isMain)=>{if(isMain&&webURL(url)){tab.url=url;saveTabs();broadcast();}});
  wc.on('page-title-updated',(_e,title)=>{tab.title=safeString(title,400);recordHistory(tab);broadcast();});
  wc.on('page-favicon-updated',(_e,icons)=>{tab.favicon=icons.find(webURL)||null;broadcast();});
  wc.on('audio-state-changed',()=>updateTab(tab,{audible:wc.isCurrentlyAudible()}));
  wc.on('did-fail-load',(_e,code,description,_url,isMain)=>{if(isMain&&code!==-3){tab.error=`This page could not load (${description}).`;tab.loading=false;broadcast();}});
  wc.on('render-process-gone',()=>{tab.error='This tab stopped. Reload to try again.';tab.loading=false;broadcast();});
  wc.on('found-in-page',(_e,result)=>event({type:'find-result',...result}));
  wc.on('dom-ready',()=>{tab.cssKey=null;applyCosmetics(tab);});
  wc.on('context-menu',(_e,p)=>{const entries=[];if(p.linkURL&&webURL(p.linkURL))entries.push({label:'Open link in new tab',click:()=>createTab(p.linkURL)},{label:'Copy link address',click:()=>require('electron').clipboard.writeText(p.linkURL)},{type:'separator'});if(p.isEditable)entries.push({role:'undo'},{role:'redo'},{type:'separator'},{role:'cut'},{role:'copy'},{role:'paste'},{role:'selectAll'});else if(p.selectionText)entries.push({role:'copy'},{label:'Search selection',click:()=>createTab(searchURL(p.selectionText,settings().searchEngine))});entries.push({type:'separator'},{label:'Back',enabled:wc.navigationHistory.canGoBack(),click:()=>wc.navigationHistory.goBack()},{label:'Reload',click:()=>wc.reload()},{label:'Pin this page',click:()=>pinCurrent()},{label:'Save bookmark',click:()=>bookmarkCurrent()},{label:'Print…',click:()=>wc.print()});Menu.buildFromTemplate(entries).popup({window:win});});
  if(load)wc.loadURL(tab.url).catch(()=>{});positionViews();return view;
}
async function applyCosmetics(tab){const wc=tab.view?.webContents;if(!wc||wc.isDestroyed())return;if(tab.cssKey){await wc.removeInsertedCSS(tab.cssKey).catch(()=>{});tab.cssKey=null;}const css=blocker?.cosmeticCSS(wc.getURL());if(css)tab.cssKey=await wc.insertCSS(css).catch(()=>null);}
function recordHistory(tab){if(!webURL(tab.url))return;const rows=store.get('history').filter(h=>h.url!==tab.url);rows.unshift({id:id(),url:tab.url,title:tab.title||tab.url,ts:Date.now()});store.set('history',rows.slice(0,5000));}
function activateTab(tabId,{split}={}){const tab=getTab(tabId);if(!tab)return;if(split){if(tab.id!==activeTabId)splitTabId=tab.id;}else {if(tab.id===splitTabId)splitTabId=activeTabId;activeTabId=tab.id;if(split===false)splitTabId=null;}tab.lastActive=Date.now();if(tab.sleeping&&!tab.page)createView(tab);positionViews();broadcast();enforceTabBudget();}
async function retireView(tab){
 const view=tab?.view;if(!view)return true;const wc=view.webContents;
 return new Promise(resolve=>{let done=false;const finish=ok=>{if(done)return;done=true;wc.removeListener('will-prevent-unload',prevent);wc.removeListener('destroyed',destroyed);if(ok){if(win&&!win.isDestroyed())win.contentView.removeChildView(view);if(tab.view===view)delete tab.view;}resolve(ok);};
 const prevent=e=>{const choice=dialog.showMessageBoxSync(win,{type:'warning',message:'Leave this page?',detail:'This page reports unsaved changes. Leaving may discard them.',buttons:['Stay on page','Leave page'],defaultId:0,cancelId:0,noLink:true});if(choice===1)e.preventDefault();else finish(false);};
 const destroyed=()=>finish(true);wc.once('will-prevent-unload',prevent);wc.once('destroyed',destroyed);wc.close({waitForBeforeUnload:true});
 });
}
async function closeTab(tabId){const tab=getTab(tabId);if(!tab)return;if(!await retireView(tab))return;const index=tabs.findIndex(t=>t.id===tabId);if(index<0)return;tabs.splice(index,1);if(webURL(tab.url))closedTabs.push({url:tab.url});if(closedTabs.length>30)closedTabs.shift();if(splitTabId===tabId)splitTabId=null;if(activeTabId===tabId)activeTabId=tabs[Math.min(index,tabs.length-1)]?.id||null;if(!tabs.length)createTab();else activateTab(activeTabId);saveTabs();}
function navigate(value,tabId=activeTabId){let tab=getTab(tabId);if(!tab)return createTab(value);const dest=navigateInput(value,settings().searchEngine);tab.url=dest.url;tab.page=dest.page;tab.error=null;if(dest.page){tab.title=dest.page==='newtab'?'New Tab':dest.page.charAt(0).toUpperCase()+dest.page.slice(1);tab.view?.webContents.stop();tab.loading=false;}else{const existing=!!tab.view;createView(tab);if(existing)tab.view.webContents.loadURL(dest.url).catch(()=>{});}positionViews();saveTabs();broadcast();return metadataTab(tab);}
function openInternal(page){if(page===null){const tab=getTab();if(tab?.view&&webURL(tab.view.webContents.getURL())){tab.page=null;tab.url=tab.view.webContents.getURL();positionViews();broadcast();}return;}if(!INTERNAL_PAGES.has(page))throw new Error('Unknown Breeze page.');return navigate('breeze://'+page);}
function goBack(){const tab=getTab();if(tab?.page&&tab.view){tab.page=null;tab.url=tab.view.webContents.getURL();positionViews();broadcast();}else if(tab?.view?.webContents.navigationHistory.canGoBack())tab.view.webContents.navigationHistory.goBack();}
function goForward(){const wc=getTab()?.view?.webContents;if(wc?.navigationHistory.canGoForward())wc.navigationHistory.goForward();}
function reloadTab(){const tab=getTab();if(!tab||tab.page)return;if(tab.sleeping)createView(tab);else if(tab.loading)tab.view?.webContents.stop();else tab.view?.webContents.reload();}
async function sleepTab(tab){if(!tab?.view||tab.id===activeTabId||tab.id===splitTabId||tab.view.webContents.isCurrentlyAudible())return false;if(!await retireView(tab))return false;tab.sleeping=true;tab.loading=false;broadcast();return true;}
async function enforceTabBudget(){const max=settings().maxLiveTabs;const live=tabs.filter(t=>t.view);if(max>0&&live.length>max){for(const tab of live.sort((a,b)=>a.lastActive-b.lastActive)){if(tabs.filter(t=>t.view).length<=max)break;if(settings().keepPinnedAppsAwake&&tab.pinned)continue;await sleepTab(tab);}}}
function pinCurrent(payload={}){const tab=getTab();const url=webURL(payload.url||tab?.url);if(!url)throw new Error('Open a website to pin it.');const pins=store.get('pins');if(!pins.some(p=>p.url===url))pins.push({id:id(),url,title:safeString(payload.title||tab?.title||url,200)});store.set('pins',pins);if(tab?.url===url)tab.pinned=true;return pins;}
function bookmarkCurrent(payload={}){const tab=getTab();const url=webURL(payload.url||tab?.url);if(!url)throw new Error('Open a website to bookmark it.');const rows=store.get('bookmarks');if(!rows.some(p=>p.url===url))rows.unshift({id:id(),url,title:safeString(payload.title||tab?.title||url,200),ts:Date.now()});store.set('bookmarks',rows);toast('Bookmark saved.');return rows;}
function zoom(value){const wc=getTab()?.view?.webContents;if(!wc)return;const cur=wc.getZoomFactor();wc.setZoomFactor(value==='0'||value===0?1:Math.min(3,Math.max(.25,cur+((value==='-'||value<0)?-.1:.1))));}
async function confirm(message,detail=''){const answer=await dialog.showMessageBox(win,{type:'question',message,detail,buttons:['Cancel','Continue'],defaultId:0,cancelId:0,noLink:true});return answer.response===1;}
function setupSession(){
 browserSession=session.fromPartition('persist:breeze-web',{cache:true});
 const rulesPath=app.isPackaged?path.join(process.resourcesPath,'easylist.json'):path.join(__dirname,'../native/easylist.json');
 blocker=createBlocker({rulesPath,getSettings:settings,getTopURL:details=>tabs.find(t=>t.view?.webContents.id===details.webContentsId)?.url||details.referrer||''});
 browserSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','ws://*/*','wss://*/*']},(details,callback)=>{let cancel=false;try{cancel=blocker.shouldBlock(details);}catch{}callback({cancel});});
 browserSession.setPermissionCheckHandler((_wc,permission,origin)=>!!settings().permissions?.[origin]?.[permission]);
 browserSession.setPermissionRequestHandler(async(wc,permission,callback,details)=>{const origin=originOf(details.requestingUrl||wc.getURL());if(!origin||origin==='null'||!['media','geolocation','notifications','fullscreen','clipboard-read','pointerLock','midi','midiSysex'].includes(permission)){callback(false);return;}if(permission==='fullscreen'){callback(true);return;}if(permission==='notifications'&&!settings().webNotifications){callback(false);return;}const granted=await confirm(`Allow ${new URL(origin).hostname} to use ${permission}?`,'Only allow permissions you trust. This choice can be cleared in Settings.');if(granted){const next=settings();next.permissions={...next.permissions,[origin]:{...next.permissions?.[origin],[permission]:true}};store.set('settings',next);}callback(granted);});
 browserSession.on('will-download',(_event,item)=>{const row={id:id(),name:item.getFilename(),url:item.getURL(),state:'progressing',receivedBytes:0,totalBytes:item.getTotalBytes(),ts:Date.now(),path:''};liveDownloads.set(row.id,item);let rows=store.get('downloads');rows.unshift(row);store.set('downloads',rows.slice(0,250));item.setSaveDialogOptions({defaultPath:path.join(app.getPath('downloads'),item.getFilename())});const update=(patch)=>{rows=store.get('downloads');const current=rows.find(r=>r.id===row.id);if(current)Object.assign(current,patch);store.set('downloads',rows);};item.on('updated',(_e,state)=>update({state,receivedBytes:item.getReceivedBytes(),totalBytes:item.getTotalBytes(),path:item.getSavePath()}));item.once('done',(_e,state)=>{liveDownloads.delete(row.id);update({state,path:item.getSavePath(),receivedBytes:item.getReceivedBytes()});toast(state==='completed'?`Downloaded ${row.name}`:`Download ${state}: ${row.name}`);});});
}
async function readPage({main=false,signal}={}){if(signal?.aborted)throw new Error('Cancelled');const wc=getTab()?.view?.webContents;if(!wc||getTab()?.page)return {title:'New Tab',url:'breeze://newtab',text:'No web page is open.',links:[]};const script=`(()=>{const root=${main?'document.querySelector("main, article, [role=main]") || document.body':'document.body'};const elements=[...document.querySelectorAll('a[href],button,input:not([type=hidden]),textarea,select,[role=button]')].filter(e=>e.getClientRects().length).slice(0,180);globalThis.__breezeElements=elements;const controls=elements.map((e,i)=>'['+(i+1)+'] '+(e.getAttribute('aria-label')||e.innerText||e.getAttribute('placeholder')||e.name||e.tagName).trim().slice(0,160)+(e.tagName==='A'?' '+e.href:'')).join('\\n');const links=[...root.querySelectorAll('a[href]')].filter(a=>/^https?:/.test(a.href)).slice(0,80).map(a=>({title:(a.innerText||a.title||a.href).trim().slice(0,180),url:a.href}));return {title:document.title,url:location.href,text:(root?.innerText||'').slice(0,28000)+'\\n\\nInteractive elements:\\n'+controls,links};})()`;return wc.executeJavaScriptInIsolatedWorld(998,[{code:script}]);}
async function waitLoaded(wc,signal){if(!wc.isLoading())return;await new Promise((resolve,reject)=>{const done=()=>{cleanup();resolve();};const stop=()=>{cleanup();reject(new Error('Cancelled'));};const cleanup=()=>{clearTimeout(timer);wc.removeListener('did-stop-loading',done);signal?.removeEventListener('abort',stop);};const timer=setTimeout(done,20000);wc.once('did-stop-loading',done);signal?.addEventListener('abort',stop,{once:true});});}
const aiTools={
 async open(url,options={}){if(options.signal?.aborted)throw new Error('Cancelled');if(!webURL(url))throw new Error('Aero can open only web URLs.');navigate(url);const wc=getTab().view.webContents;await waitLoaded(wc,options.signal);return readPage(options);},
 async search(query,options={}){return aiTools.open(searchURL(query,settings().searchEngine),options);},
 read:readPage,
 async click(target,options={}){if(options.signal?.aborted)throw new Error('Cancelled');const wc=getTab()?.view?.webContents;if(!wc)throw new Error('Open a web page first.');if(!await confirm('Allow Aero to click this page element?',`${wc.getURL()}\nElement: ${safeString(String(target),300)}`))throw new Error('Click cancelled.');if(options.signal?.aborted)throw new Error('Cancelled');const result=await wc.executeJavaScriptInIsolatedWorld(998,[{code:`(()=>{const t=${JSON.stringify(String(target))};const n=Number(t.replace(/[\\[\\]]/g,''));const es=globalThis.__breezeElements||[];const e=Number.isInteger(n)?es[n-1]:es.find(e=>(e.innerText||e.getAttribute('aria-label')||'').trim().toLowerCase()===t.toLowerCase());if(!e)throw new Error('Element no longer exists. Read the page again.');e.click();return 'Clicked '+t;})()`}]);await waitLoaded(wc,options.signal);return {text:result,...await readPage()};},
 async type(target,text,options={}){if(options.signal?.aborted)throw new Error('Cancelled');const wc=getTab()?.view?.webContents;if(!wc)throw new Error('Open a web page first.');if(!await confirm('Allow Aero to type into this page?',`${wc.getURL()}\nField: ${safeString(String(target),300)}\nText: ${safeString(text,300)}`))throw new Error('Typing cancelled.');if(options.signal?.aborted)throw new Error('Cancelled');await wc.executeJavaScriptInIsolatedWorld(998,[{code:`(()=>{const t=${JSON.stringify(String(target))};const n=Number(t.replace(/[\\[\\]]/g,''));const es=globalThis.__breezeElements||[];const e=Number.isInteger(n)?es[n-1]:es.find(e=>(e.name||e.placeholder||'').toLowerCase()===t.toLowerCase());if(!e||!['INPUT','TEXTAREA','SELECT'].includes(e.tagName))throw new Error('Editable field not found.');if(e.type==='password'||/cc-|credit|card|otp|one-time-code/i.test(e.autocomplete+' '+e.name))throw new Error('Enter sensitive credentials yourself.');const setter=Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')?.set;const value=${JSON.stringify(safeString(text,12000))};if(setter)setter.call(e,value);else e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));return true;})()`}]);return readPage();},
 async look(options={}){if(options.signal?.aborted)throw new Error('Cancelled');const wc=getTab()?.view?.webContents;if(!wc)throw new Error('Open a page first.');const image=(await wc.capturePage()).toDataURL();return {...await readPage(options),image};},
 async remind(minutes,text){const reminder=addReminder({minutes,text});return 'Reminder set for '+reminder.dueAt;}
};
function addReminder(payload){const text=safeString(payload.text,2000).trim();const due=payload.dueAt?Date.parse(payload.dueAt):Date.now()+Number(payload.minutes)*60000;if(!text||!Number.isFinite(due)||due<=Date.now())throw new Error('Choose a future time and reminder text.');const row={id:id(),text,dueAt:new Date(due).toISOString(),fired:false};store.set('reminders',[...store.get('reminders'),row]);scheduleReminder(row);return row;}
function scheduleReminder(row){clearTimeout(reminderTimers.get(row.id));if(row.fired)return;const delay=Math.max(0,Date.parse(row.dueAt)-Date.now());const timer=setTimeout(()=>{if(delay>2147000000){scheduleReminder(row);return;}const rows=store.get('reminders');const found=rows.find(r=>r.id===row.id);if(!found)return;found.fired=true;store.set('reminders',rows);if(Notification.isSupported())new Notification({title:'Breeze reminder',body:found.text}).show();toast(found.text);},Math.min(delay,2147000000));reminderTimers.set(row.id,timer);}
async function refreshPasswords(){try{passwordMetadata=(await vault.listPasswords()).map(p=>({...p,url:p.origin}));}catch{passwordMetadata=[];}broadcast();}
async function handleAuthURL(url){if(!url||!cloud)return;try{await cloud.account.finishAuthCallback(url);cloudState=cloud.account.state();broadcast();}catch{toast('Breeze Cloud sign-in could not complete.','error');}}
async function sendAssistant(payload){if(assistant.running)throw new Error('Stop the current reply before sending another message.');const text=safeString(payload.text,12000).trim();if(!text)return;const generation=++assistantGeneration;assistant.visible=true;assistant.error=null;assistant.running=true;assistant.chatId??=id();const previous=assistant.messages.slice();assistant.messages.push({role:'user',text,time:Date.now()});broadcast();try{const contexts=[];if(!getTab()?.page)contexts.push({...await readPage(),isCurrent:true});for(const tabId of (payload.tabIds||[]).slice(0,8)){const tab=getTab(tabId);if(tab?.view&&tab.id!==activeTabId)contexts.push({title:tab.title,url:tab.url,text:await tab.view.webContents.executeJavaScript('document.body.innerText.slice(0,12000)')});}const s=settings();if(s.aiIncludeHistory)contexts.push({title:'Recent browsing history',text:JSON.stringify(store.get('history').slice(0,30))});if(s.aiIncludeBookmarks)contexts.push({title:'Bookmarks',text:JSON.stringify(store.get('bookmarks').slice(0,100))});if(s.aiIncludeOpenTabs)contexts.push({title:'Open tabs',text:JSON.stringify(tabs.map(metadataTab))});if(generation!==assistantGeneration)return;const result=await cloud.aero.send({text,history:s.aiUseChatHistory?previous:[],contexts,images:assistant.attachments.map(a=>a.data)});if(generation!==assistantGeneration)return;assistant.messages.push({role:'ai',text:result.answer||result.text,chips:result.chips,sources:result.sources,time:Date.now()});assistant.attachments=[];const chats=store.get('chats').filter(c=>c.id!==assistant.chatId);chats.unshift({id:assistant.chatId,title:assistant.messages.find(m=>m.role==='user')?.text.slice(0,80)||'Aero chat',messages:assistant.messages,time:Date.now()});store.set('chats',chats.slice(0,200));}catch(error){if(generation===assistantGeneration&&error.name!=='AbortError'&&!/cancel/i.test(error.message)){assistant.error=error.message;}}finally{if(generation===assistantGeneration){assistant.running=false;assistant.status='';broadcast();}}}
async function execute(action,payload={}){
 if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('Invalid request.');
 switch(action){
 case 'state:get':return snapshot();
 case 'window:minimize':win.minimize();return;
 case 'window:maximize':win.isMaximized()?win.unmaximize():win.maximize();return;
 case 'window:close':win.close();return;
 case 'browser:layout':layout={...payload};positionViews();return;
 case 'browser:internal':return openInternal(payload.page);
 case 'browser:find':{const wc=getTab()?.view?.webContents;if(!wc)return;if(payload.close||payload.stop||!payload.text){wc.stopFindInPage('clearSelection');return;}wc.findInPage(safeString(payload.text,500),{forward:payload.forward!==false,findNext:payload.findNext!==false,matchCase:!!payload.matchCase});return;}
 case 'browser:zoom':return zoom(payload.factor===1?0:(payload.value??payload.delta??0));
 case 'browser:print':return getTab()?.view?.webContents.print();
 case 'browser:restore':{const rows=restoreTabs;restoreTabs=[];if(payload.restore!==false)for(const row of rows)createTab(row.url,{activate:false,groupId:row.groupId});saveTabs();broadcast();return;}
 case 'browser:clearData':{if(!await confirm('Clear browsing cookies, cache, and site permissions?','You will be signed out of websites. Bookmarks, Cloud account, and saved passwords stay in place.'))return;await browserSession.clearStorageData();await browserSession.clearCache();const s=settings();s.permissions={};store.set('settings',s);toast('Website data cleared.');return;}
 case 'browser:update':{createTab('https://github.com/Froydinger/breezebrowser-live/releases/tag/windows-v'+app.getVersion());toast('Windows updates are installed from a versioned Breeze release.');return;}
 case 'tab:new':return createTab(payload.url||'breeze://newtab',{split:!!payload.split,groupId:payload.groupId||null,pinned:!!payload.pinned});
 case 'tab:activate':return activateTab(payload.id,{split:payload.split});
 case 'tab:close':return closeTab(payload.id||activeTabId);
 case 'tab:navigate':return navigate(payload.url??payload.value??payload.text,payload.id||activeTabId);
 case 'tab:back':return goBack();case 'tab:forward':return goForward();case 'tab:reload':return reloadTab();
 case 'tab:duplicate':{const tab=getTab(payload.id);if(tab)return createTab(tab.url,{groupId:tab.groupId});return;}
 case 'tab:mute':{const tab=getTab(payload.id);if(tab){tab.muted=payload.muted??!tab.muted;tab.view?.webContents.setAudioMuted(tab.muted);broadcast();}return;}
 case 'tab:sleep':{const tab=getTab(payload.id);if(payload.sleeping===false&&tab?.sleeping){createView(tab);broadcast();return true;}return sleepTab(tab);}
 case 'pin:add':return pinCurrent(payload);
 case 'pin:remove':{store.set('pins',store.get('pins').filter(p=>p.id!==payload.id&&p.url!==payload.url));for(const tab of tabs)tab.pinned=store.get('pins').some(p=>p.url===tab.url);broadcast();return;}
 case 'group:create':{const group={id:id(),title:safeString(payload.title||'New group',80),color:/^#[\da-f]{6}$/i.test(payload.color)?payload.color:'#3aa6b9',collapsed:false};store.set('groups',[...store.get('groups'),group]);if(payload.tabId){const tab=getTab(payload.tabId);if(tab)tab.groupId=group.id;}broadcast();return group;}
 case 'group:update':{const groups=store.get('groups');const group=groups.find(g=>g.id===payload.id);if(group){if(payload.remove){store.set('groups',groups.filter(g=>g.id!==payload.id));for(const tab of tabs)if(tab.groupId===payload.id)tab.groupId=null;}else{if(typeof payload.title==='string')group.title=payload.title.slice(0,80);if(typeof payload.collapsed==='boolean')group.collapsed=payload.collapsed;if(/^#[\da-f]{6}$/i.test(payload.color))group.color=payload.color;store.set('groups',groups);}}broadcast();return;}
 case 'group:assign':{const tab=getTab(payload.tabId||payload.id);if(tab){tab.groupId=store.get('groups').some(g=>g.id===payload.groupId)?payload.groupId:null;saveTabs();broadcast();}return;}
 case 'settings:update':{const patch={...(payload.patch||payload)};if(patch.cloudSync){for(const [key,enabled] of Object.entries(patch.cloudSync))await cloud.account.setSyncPreference(key,enabled);delete patch.cloudSync;cloudState=cloud.account.state();}const result=store.updateSettings(patch);applyTheme();if(Object.keys(patch).some(k=>k.startsWith('adblock')))for(const tab of tabs)void applyCosmetics(tab);broadcast();return result;}
 case 'bookmark:add':return bookmarkCurrent(payload);
 case 'bookmark:remove':store.set('bookmarks',store.get('bookmarks').filter(b=>b.id!==payload.id&&b.url!==payload.url));return;
 case 'history:clear':{if(await confirm('Clear browsing history?','This removes the history saved in this Windows profile.'))store.set('history',[]);return;}
 case 'downloads:cancel':liveDownloads.get(payload.id)?.cancel();return;
 case 'downloads:show':case 'downloads:open':{const row=store.get('downloads').find(d=>d.id===payload.id);if(!row?.path||row.state!=='completed'||!fs.existsSync(row.path))throw new Error('That download is not available.');if(action==='downloads:show')shell.showItemInFolder(row.path);else{if(/\.(exe|msi|bat|cmd|ps1|vbs|scr|com)$/i.test(row.path)&&!await confirm('Open this downloaded program?',row.name+'\nOnly run software you trust.'))return;const error=await shell.openPath(row.path);if(error)throw new Error(error);}return;}
 case 'passwords:list':await refreshPasswords();return passwordMetadata;
 case 'passwords:save':{await vault.savePassword({...payload,origin:originOf(payload.origin||payload.url)});await refreshPasswords();changed('passwords');return passwordMetadata;}
 case 'passwords:reveal':{if(!await confirm('Reveal this saved password?','Make sure no one else can see your screen.'))return null;return vault.revealPassword(payload.id);}
 case 'passwords:remove':{if(!await confirm('Remove this saved password?'))return;await vault.deletePassword(payload.id);await refreshPasswords();changed('passwords');return;}
 case 'passwords:fill':{const tab=getTab();const current=webURL(tab?.url);if(!current||!tab?.view)throw new Error('Open the matching website first.');const entry=await vault.revealPassword(payload.id);if(!entry||originOf(entry.origin)!==originOf(current))throw new Error('The saved password does not match this website.');if(!await confirm(`Fill your saved sign-in for ${new URL(current).hostname}?`,'Breeze will fill the fields. You will submit the sign-in yourself.'))return;await tab.view.webContents.executeJavaScriptInIsolatedWorld(998,[{code:`(()=>{if(location.origin!==${JSON.stringify(originOf(current))})throw new Error('Page changed.');const p=document.querySelector('input[type=password]');if(!p)throw new Error('Password field not found.');const u=(p.form||document).querySelector('input[autocomplete=username],input[type=email],input[name*=user i],input[type=text]');for(const [e,v] of [[u,${JSON.stringify(entry.username)}],[p,${JSON.stringify(entry.password)}]]){if(e){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,v);e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}}return true;})()`}]);return;}
 case 'cloud:signIn':case 'cloud:signUp':{await cloud.ready;const method=action==='cloud:signIn'?'signIn':'signUp';const result=await cloud.account[method]({email:safeString(payload.email,254),password:safeString(payload.password,1024)});cloudState=cloud.account.state();broadcast();return result;}
 case 'cloud:signOut':await cloud.account.signOut();cloudState=cloud.account.state();broadcast();return;
 case 'cloud:sync':await cloud.account.syncNow();cloudState=cloud.account.state();await refreshPasswords();broadcast();return cloudState;
 case 'cloud:export':{const data=await cloud.account.exportCloudData();const chosen=await dialog.showSaveDialog(win,{title:'Export Breeze Cloud data',defaultPath:path.join(app.getPath('documents'),'Breeze-Cloud-export.json'),filters:[{name:'JSON',extensions:['json']}]});if(chosen.canceled||!chosen.filePath)return;fs.writeFileSync(chosen.filePath,JSON.stringify(data,null,2),{mode:0o600});toast('Breeze Cloud data exported.');return;}
 case 'cloud:deleteAccount':{if(payload.confirmation!=='DELETE')throw new Error('Type DELETE to confirm account removal.');if(!await confirm('Permanently delete your Breeze Cloud account?', 'Your account and cloud data will be removed permanently. This cannot be undone. Device-only passwords are retained.'))return;await cloud.account.deleteAccount({confirmed:true});cloudState=cloud.account.state();broadcast();return;}
 case 'cloud:syncPreference':await cloud.account.setSyncPreference(payload.key||payload.collection,payload.enabled);cloudState=cloud.account.state();broadcast();return cloudState;
 case 'cloud:google':{const result=await cloud.account.beginGoogleSignIn();const url=typeof result==='string'?result:result.url;if(!webURL(url))throw new Error('Could not start Google sign-in.');await shell.openExternal(url);return;}
 case 'assistant:open':{assistant.visible=payload.visible!==false;if(payload.id&&payload.id!==assistant.chatId){++assistantGeneration;cloud.aero.cancel();assistant.running=false;assistant.status='';const chat=store.get('chats').find(c=>c.id===payload.id);if(chat){assistant.chatId=chat.id;assistant.messages=chat.messages||[];}}assistant.fullscreen=!!payload.fullscreen;positionViews();broadcast();return;}
 case 'assistant:new':++assistantGeneration;cloud.aero.cancel();assistant.running=false;assistant.chatId=id();assistant.messages=[];assistant.attachments=[];assistant.error=null;assistant.visible=true;broadcast();return;
 case 'assistant:stop':++assistantGeneration;cloud.aero.cancel();assistant.running=false;assistant.status='Stopped';broadcast();return;
 case 'assistant:send':void sendAssistant(payload);return;
 case 'assistant:attach':{if(payload.removeId){assistant.attachments=assistant.attachments.filter(a=>a.id!==payload.removeId);broadcast();return;}const result=await dialog.showOpenDialog(win,{title:'Attach images for Aero',properties:['openFile','multiSelections'],filters:[{name:'Images',extensions:['png','jpg','jpeg','webp']}]});if(result.canceled)return;for(const file of result.filePaths.slice(0,4-assistant.attachments.length)){const data=fs.readFileSync(file);if(data.length>8*1024*1024)throw new Error('Choose images smaller than 8 MB.');const ext=path.extname(file).toLowerCase();const mime=ext==='.png'?'image/png':ext==='.webp'?'image/webp':'image/jpeg';assistant.attachments.push({id:id(),name:path.basename(file),data:'data:'+mime+';base64,'+data.toString('base64')});}broadcast();return;}
 case 'reminder:add':return addReminder(payload);
 case 'reminder:remove':clearTimeout(reminderTimers.get(payload.id));reminderTimers.delete(payload.id);store.set('reminders',store.get('reminders').filter(r=>r.id!==payload.id));return;
 default:throw new Error('Unsupported Breeze action.');
 }
}
async function start(){
 store=new Store(app.getPath('userData'));restoreTabs=settings().restoreTabs==='never'?[]:store.get('openTabs');
 vault=createVault({safeStorage,store});
 win=new BrowserWindow({width:1440,height:950,minWidth:900,minHeight:620,frame:false,show:false,backgroundColor:'#000000',title:config.development?'Breeze Test':'Breeze',icon:path.join(__dirname,'assets/icon.ico'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false,webSecurity:true,allowRunningInsecureContent:false,webviewTag:false}});
 win.setMenu(null);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.on('will-attach-webview',e=>e.preventDefault());hookKeys(win.webContents);
 win.on('resize',()=>{positionViews();event({type:'resize'});});win.on('maximize',broadcast);win.on('unmaximize',broadcast);win.on('close',e=>{if(quitting)return;e.preventDefault();if(closingWindow)return;closingWindow=true;saveTabs();(async()=>{for(const tab of tabs){if(!await retireView(tab)){closingWindow=false;for(const item of tabs)if(!item.view&&!item.page)item.sleeping=true;activateTab(activeTabId);broadcast();return;}}quitting=true;win.destroy();app.quit();})().catch(()=>{closingWindow=false;});});
 setupSession();
 cloud=createCloud({config,store,vault,fetch:(...args)=>net.fetch(...args),tools:aiTools,onEvent:e=>{if(e.type==='account'){cloudState=e.state||cloud.account.state();}else if(e.type==='status'){assistant.status=e.status;}event(e);broadcast();},onChange:(collection,rows)=>{if(collection==='reminders'){for(const timer of reminderTimers.values())clearTimeout(timer);reminderTimers.clear();for(const row of rows)scheduleReminder(row);}if(collection==='passwords')void refreshPasswords();else if(collection==='tabs'||collection==='openTabs')restoreTabs=rows;else if(Array.isArray(rows)&&['bookmarks','pins','history','chats','reminders'].includes(collection))store.set(collection,rows);broadcast();}});
 Promise.resolve(cloud.ready).then(()=>{cloudState=cloud.account.state();refreshPasswords();broadcast();if(cloudState.signedIn)cloud.account.syncNow().catch(()=>{});}).catch(error=>{cloudState={configured:false,error:error.message};broadcast();});
 ipcMain.handle('breeze:invoke',async(e,action,payload)=>{if(e.sender!==win.webContents||e.senderFrame!==win.webContents.mainFrame||e.senderFrame.url!==APP_URL)throw new Error('Untrusted Breeze bridge sender.');if(typeof action!=='string'||JSON.stringify(payload||{}).length>60000)throw new Error('Invalid Breeze request.');return execute(action,payload);});
 store.subscribe(changed);nativeTheme.on('updated',broadcast);applyTheme();
 if(settings().restoreTabs==='always'){for(const row of restoreTabs)if(webURL(row.url))createTab(row.url,{activate:false,groupId:row.groupId,pinned:row.pinned});restoreTabs=[];}
 if(!tabs.length)createTab(settings().hasOnboarded?'breeze://newtab':'breeze://onboarding');else activateTab(tabs[0].id);
 for(const row of store.get('reminders'))scheduleReminder(row);
 if(process.platform==='win32'&&app.isPackaged&&!config.development)app.setAsDefaultProtocolClient('com.froydinger.breeze');
 await win.loadURL(APP_URL);win.show();broadcast();
 const callback=process.argv.find(a=>a.match(/^com\.froydinger\.breeze:/));if(callback)handleAuthURL(callback);
 if(process.argv.includes('--smoke-test'))await runSmokeTest();
}
if(gotLock)app.whenReady().then(start).catch(error=>{console.error('Breeze could not start:',error.message);if(process.argv.includes('--smoke-test')){fs.writeFileSync(path.resolve('smoke-result.json'),JSON.stringify({ok:false,error:error.message}));app.exit(1);}else dialog.showErrorBox('Breeze could not start',error.message);});
async function runSmokeTest(){
 const assert=require('node:assert/strict');const http=require('node:http');const checks=[];let server;
 try{
  server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end('<!doctype html><title>Breeze fixture '+req.url+'</title><main><h1>Breeze Chromium works</h1><a href="/next">Next page</a><input placeholder="Test input"><button>Test button</button></main>');});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
  assert.equal((await win.webContents.executeJavaScript('typeof window.breeze.invoke')),'function');checks.push('trusted shell bridge');
  const tab=createTab(url);await waitLoaded(getTab(tab.id).view.webContents);const wc=getTab(tab.id).view.webContents;
  assert.deepEqual(await wc.executeJavaScript('({node:typeof require,bridge:typeof window.breeze,process:typeof process})'),{node:'undefined',bridge:'undefined',process:'undefined'});checks.push('remote Node and bridge isolation');
  const read=await readPage();assert.match(read.text,/Breeze Chromium works/);assert.ok(read.links.some(l=>l.url.endsWith('/next')));checks.push('page reading and elements');
  navigate(url+'/next');await waitLoaded(wc);assert.ok(wc.navigationHistory.canGoBack());goBack();await waitLoaded(wc);assert.equal(new URL(wc.getURL()).pathname,'/');checks.push('navigation back');
  bookmarkCurrent();assert.ok(store.get('bookmarks').some(b=>b.url.startsWith(url)));pinCurrent();assert.ok(store.get('pins').some(b=>b.url.startsWith(url)));checks.push('bookmarks and pins');
  const group=await execute('group:create',{title:'Test'});await execute('group:assign',{tabId:tab.id,groupId:group.id});assert.equal(getTab(tab.id).groupId,group.id);checks.push('tab groups');
  const second=createTab(url+'/second');await waitLoaded(getTab(second.id).view.webContents);activateTab(tab.id,{split:true});assert.equal(splitTabId,tab.id);checks.push('split view');
  splitTabId=null;assert.equal(await sleepTab(getTab(tab.id)),true);activateTab(tab.id);await waitLoaded(getTab(tab.id).view.webContents);assert.equal(getTab(tab.id).sleeping,false);checks.push('sleep and restore tab');
  await execute('settings:update',{theme:'dark'});assert.equal(settings().theme,'dark');openInternal('settings');assert.equal(getTab().page,'settings');checks.push('internal pages and settings');
  let blocked=false;try{navigate('file:///C:/Windows/win.ini');}catch{blocked=true;}assert.ok(blocked);checks.push('unsafe URL blocked');
  await win.webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
  assert.match(await win.webContents.executeJavaScript('document.querySelector("#page-content").innerText'),/Settings/);checks.push('settings renderer');
  openInternal('newtab');await win.webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
  assert.match(await win.webContents.executeJavaScript('document.querySelector("#page-content").innerText'),/exploring/);checks.push('new-tab renderer');
  if(process.platform==='win32'){await vault.ready;const testPassword='synthetic-smoke-'+id();const saved=await vault.savePassword({origin:'https://example.test',username:'breeze-smoke',password:testPassword});assert.equal((await vault.revealPassword(saved.id)).password,testPassword);assert.ok(!JSON.stringify(store.get('secureVault')).includes(testPassword));await vault.deletePassword(saved.id);checks.push('Windows DPAPI vault round-trip');}
  const image=await win.webContents.capturePage();fs.writeFileSync(path.resolve('smoke-screenshot.png'),image.toPNG());
  fs.writeFileSync(path.resolve('smoke-result.json'),JSON.stringify({ok:true,checks,version:app.getVersion(),chromium:process.versions.chrome},null,2));console.log('Breeze smoke checks passed: '+checks.join(', '));server.close();app.exit(0);
 }catch(error){fs.writeFileSync(path.resolve('smoke-result.json'),JSON.stringify({ok:false,checks,error:error.stack},null,2));console.error('Breeze smoke test failed:',error);server?.close();app.exit(1);}
}
