const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('breeze', {
  newTab: () => ipcRenderer.send('new-tab'),
  closeTab: (id) => ipcRenderer.send('close-tab', id),
  activateTab: (id) => ipcRenderer.send('activate-tab', id),
  navigate: (input) => ipcRenderer.send('navigate', input),
  openURL: (url) => ipcRenderer.send('open-url', url),
  openURLNewTab: (url) => ipcRenderer.send('open-url-new-tab', url),
  goBack: () => ipcRenderer.send('go-back'),
  goForward: () => ipcRenderer.send('go-forward'),
  reload: () => ipcRenderer.send('reload'),
  toggleSidebar: () => ipcRenderer.send('toggle-sidebar'),
  peekSidebar: () => ipcRenderer.send('peek-sidebar'),
  endPeek: () => ipcRenderer.send('end-peek'),
  onSidebarPeek: (cb) => ipcRenderer.on('sidebar-peek', (_e, v) => cb(v)),
  toggleAssistant: () => ipcRenderer.send('toggle-assistant'),
  toggleBookmark: () => ipcRenderer.send('toggle-bookmark'),
  toggleSiteNotif: (origin) => ipcRenderer.send('toggle-site-notif', origin),
  removeBookmark: (url) => ipcRenderer.send('remove-bookmark', url),
  setTheme: (theme) => ipcRenderer.send('set-theme', theme),
  setSetting: (key, value) => ipcRenderer.send('set-setting', { key, value }),
  onboardingActive: (active) => ipcRenderer.send('onboarding-active', active),
  openSettings: (section) => ipcRenderer.send('open-settings', section),
  omniboxOverlay: (h) => ipcRenderer.send('omnibox-overlay', h),
  clearTabData: () => ipcRenderer.send('clear-tab-data'),
  openDownloads: () => ipcRenderer.send('open-downloads'),
  openBookmarks: () => ipcRenderer.send('open-bookmarks'),
  pinTab: (id) => ipcRenderer.send('pin-tab', id),
  openHistory: () => ipcRenderer.send('open-history'),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, s) => cb(s)),
  setSidebarWidth: (w) => ipcRenderer.send('set-sidebar-width', w),
  saveSidebarWidth: () => ipcRenderer.send('save-sidebar-width'),
  tabContextMenu: (id) => ipcRenderer.send('tab-context-menu', id),
  openPin: (url) => ipcRenderer.send('open-pin', url),
  pinContextMenu: (url) => ipcRenderer.send('pin-context-menu', url),
  reorderPins: (urls) => ipcRenderer.send('reorder-pins', urls),
  reorderTabs: (ids) => ipcRenderer.send('reorder-tabs', ids),
  enterSplit: (id) => ipcRenderer.send('enter-split', id),
  exitSplit: () => ipcRenderer.send('exit-split'),
  setSplitRatio: (r) => ipcRenderer.send('set-split-ratio', r),
  onSplit: (cb) => ipcRenderer.on('split', (_e, v) => cb(v)),
  onSplitDivider: (cb) => ipcRenderer.on('split-divider', (_e, d) => cb(d)),
  onSplitBars: (cb) => ipcRenderer.on('split-bars', (_e, d) => cb(d)),
  tabNav: (id, action) => ipcRenderer.send('tab-nav', { id, action }),
  tabNavigate: (id, input) => ipcRenderer.send('tab-navigate', { id, input }),
  toggleGroupCollapse: (gid) => ipcRenderer.send('toggle-group-collapse', gid),
  onDownloads: (cb) => ipcRenderer.on('downloads', (_e, d) => cb(d)),
  getReminders: () => ipcRenderer.invoke('get-reminders'),
  deleteReminder: (id) => ipcRenderer.send('delete-reminder', id),
  confirmDeleteReminder: (id) => ipcRenderer.invoke('delete-reminder-confirm', id),
  onReminders: (cb) => ipcRenderer.on('reminders-changed', (_e, r) => cb(r)),
  openGroupEntry: (gid, eid) => ipcRenderer.send('open-group-entry', { gid, eid }),
  renameGroup: (gid, name) => ipcRenderer.send('rename-group', { gid, name }),
  groupEntryMenu: (gid, eid) => ipcRenderer.send('group-entry-menu', { gid, eid }),
  groupHeaderMenu: (gid) => ipcRenderer.send('group-header-menu', gid),
  onRenameGroupStart: (cb) => ipcRenderer.on('rename-group-start', (_e, gid) => cb(gid)),
  onNowPlaying: (cb) => ipcRenderer.on('now-playing', (_e, p) => cb(p)),
  mediaToggle: (id) => ipcRenderer.send('media-toggle', id),
  mediaBackToTab: (id) => ipcRenderer.send('media-back-to-tab', id),
  mediaPiP: (id) => ipcRenderer.send('media-pip', id),
  installUpdate: () => ipcRenderer.send('install-update'),
  getInit: () => ipcRenderer.invoke('get-init'),
  getSuggestions: (q) => ipcRenderer.invoke('get-suggestions', q),

  aiAsk: (opts) => ipcRenderer.send('ai-ask', opts),
  aiStop: () => ipcRenderer.send('ai-stop'),
  aiWebConsent: (ok) => ipcRenderer.send('ai-web-consent-reply', ok),
  downloadImage: (src) => ipcRenderer.send('download-image', src),
  aiNewChat: () => ipcRenderer.send('ai-new-chat'),
  chatList: () => ipcRenderer.invoke('chat-list'),
  chatLoad: (id) => ipcRenderer.invoke('chat-load', id),
  chatSave: (chat) => ipcRenderer.send('chat-save', chat),
  chatDelete: (id) => ipcRenderer.send('chat-delete', id),
  onChatsChanged: (cb) => ipcRenderer.on('chats-changed', () => cb()),

  onState: (cb) => ipcRenderer.on('state', (_e, s) => cb(s)),
  onTheme: (cb) => ipcRenderer.on('theme', (_e, t) => cb(t)),
  onSidebar: (cb) => ipcRenderer.on('sidebar', (_e, v) => cb(v)),
  onAssistant: (cb) => ipcRenderer.on('assistant', (_e, v) => cb(v)),
  onFullscreen: (cb) => ipcRenderer.on('app-fullscreen', (_e, v) => cb(v)),
  onCornerPeek: (cb) => ipcRenderer.on('corner-peek', (_e, v) => cb(v)),
  onFocusAddress: (cb) => ipcRenderer.on('focus-address', () => cb()),
  onAdblockCount: (cb) => ipcRenderer.on('adblock-count', (_e, n) => cb(n)),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', () => cb()),
  onAIStatus: (cb) => ipcRenderer.on('ai-status', (_e, s) => cb(s)),
  onAIChunk: (cb) => ipcRenderer.on('ai-chunk', (_e, c) => cb(c)),
  onAIDone: (cb) => ipcRenderer.on('ai-done', () => cb()),
  onAICleared: (cb) => ipcRenderer.on('ai-cleared', () => cb()),
  onAITool: (cb) => ipcRenderer.on('ai-tool', (_e, t) => cb(t)),
  onAISearch: (cb) => ipcRenderer.on('ai-search', (_e, s) => cb(s)),
  onAIWebConsent: (cb) => ipcRenderer.on('ai-web-consent', (_e, q) => cb(q)),
  onAIImage: (cb) => ipcRenderer.on('ai-image', (_e, src) => cb(src)),
  onPageSelection: (cb) => ipcRenderer.on('page-selection', (_e, t) => cb(t)),
});
