const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('breeze', {
  newTab: () => ipcRenderer.send('new-tab'),
  closeTab: (id) => ipcRenderer.send('close-tab', id),
  activateTab: (id) => ipcRenderer.send('activate-tab', id),
  navigate: (input) => ipcRenderer.send('navigate', input),
  openURL: (url) => ipcRenderer.send('open-url', url),
  openURLNewTab: (url) => ipcRenderer.send('open-url-new-tab', url),
  goBack: () => ipcRenderer.send('go-back'),
  goForward: () => ipcRenderer.send('go-forward'),
  reload: () => ipcRenderer.send('reload'),
  toggleSidebar: () => ipcRenderer.send('toggle-sidebar'),
  toggleAssistant: () => ipcRenderer.send('toggle-assistant'),
  toggleBookmark: () => ipcRenderer.send('toggle-bookmark'),
  removeBookmark: (url) => ipcRenderer.send('remove-bookmark', url),
  setTheme: (theme) => ipcRenderer.send('set-theme', theme),
  openSettings: () => ipcRenderer.send('open-settings'),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, s) => cb(s)),
  installUpdate: () => ipcRenderer.send('install-update'),
  getInit: () => ipcRenderer.invoke('get-init'),

  aiAsk: (text, includePage) => ipcRenderer.send('ai-ask', { text, includePage }),
  aiStop: () => ipcRenderer.send('ai-stop'),
  aiNewChat: () => ipcRenderer.send('ai-new-chat'),

  onState: (cb) => ipcRenderer.on('state', (_e, s) => cb(s)),
  onTheme: (cb) => ipcRenderer.on('theme', (_e, t) => cb(t)),
  onSidebar: (cb) => ipcRenderer.on('sidebar', (_e, v) => cb(v)),
  onAssistant: (cb) => ipcRenderer.on('assistant', (_e, v) => cb(v)),
  onFocusAddress: (cb) => ipcRenderer.on('focus-address', () => cb()),
  onAdblockCount: (cb) => ipcRenderer.on('adblock-count', (_e, n) => cb(n)),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', () => cb()),
  onAIStatus: (cb) => ipcRenderer.on('ai-status', (_e, s) => cb(s)),
  onAIChunk: (cb) => ipcRenderer.on('ai-chunk', (_e, c) => cb(c)),
  onAIDone: (cb) => ipcRenderer.on('ai-done', () => cb()),
  onAICleared: (cb) => ipcRenderer.on('ai-cleared', () => cb()),
});
