const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('breeze', {
  newTab: () => ipcRenderer.send('new-tab'),
  closeTab: (id) => ipcRenderer.send('close-tab', id),
  activateTab: (id) => ipcRenderer.send('activate-tab', id),
  navigate: (input) => ipcRenderer.send('navigate', input),
  openURL: (url) => ipcRenderer.send('open-url', url),
  openURLNewTab: (url) => ipcRenderer.send('open-url-new-tab', url),
  goBack: () => ipcRenderer.send('go-back'),
  goForward: () => ipcRenderer.send('go-forward'),
  reload: () => ipcRenderer.send('reload'),
  toggleSidebar: () => ipcRenderer.send('toggle-sidebar'),
  peekSidebar: () => ipcRenderer.send('peek-sidebar'),
  endPeek: () => ipcRenderer.send('end-peek'),
  onSidebarPeek: (cb) => ipcRenderer.on('sidebar-peek', (_e, v) => cb(v)),
  toggleAssistant: () => ipcRenderer.send('toggle-assistant'),
  toggleBookmark: () => ipcRenderer.send('toggle-bookmark'),
  removeBookmark: (url) => ipcRenderer.send('remove-bookmark', url),
  setTheme: (theme) => ipcRenderer.send('set-theme', theme),
  openSettings: () => ipcRenderer.send('open-settings'),
  openDownloads: () => ipcRenderer.send('open-downloads'),
  openBookmarks: () => ipcRenderer.send('open-bookmarks'),
  pinTab: (id) => ipcRenderer.send('pin-tab', id),
  openHistory: () => ipcRenderer.send('open-history'),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, s) => cb(s)),
  setSidebarWidth: (w) => ipcRenderer.send('set-sidebar-width', w),
  saveSidebarWidth: () => ipcRenderer.send('save-sidebar-width'),
  tabContextMenu: (id) => ipcRenderer.send('tab-context-menu', id),
  openPin: (url) => ipcRenderer.send('open-pin', url),
  pinContextMenu: (url) => ipcRenderer.send('pin-context-menu', url),
  onDownloads: (cb) => ipcRenderer.on('downloads', (_e, d) => cb(d)),
  openGroupEntry: (gid, eid) => ipcRenderer.send('open-group-entry', { gid, eid }),
  renameGroup: (gid, name) => ipcRenderer.send('rename-group', { gid, name }),
  groupEntryMenu: (gid, eid) => ipcRenderer.send('group-entry-menu', { gid, eid }),
  groupHeaderMenu: (gid) => ipcRenderer.send('group-header-menu', gid),
  onRenameGroupStart: (cb) => ipcRenderer.on('rename-group-start', (_e, gid) => cb(gid)),
  onNowPlaying: (cb) => ipcRenderer.on('now-playing', (_e, p) => cb(p)),
  mediaToggle: (id) => ipcRenderer.send('media-toggle', id),
  mediaBackToTab: (id) => ipcRenderer.send('media-back-to-tab', id),
  mediaPiP: (id) => ipcRenderer.send('media-pip', id),
  installUpdate: () => ipcRenderer.send('install-update'),
  getInit: () => ipcRenderer.invoke('get-init'),
  getSuggestions: (q) => ipcRenderer.invoke('get-suggestions', q),

  aiAsk: (text, useWeb) => ipcRenderer.send('ai-ask', { text, useWeb }),
  aiStop: () => ipcRenderer.send('ai-stop'),
  aiNewChat: () => ipcRenderer.send('ai-new-chat'),

  onState: (cb) => ipcRenderer.on('state', (_e, s) => cb(s)),
  onTheme: (cb) => ipcRenderer.on('theme', (_e, t) => cb(t)),
  onSidebar: (cb) => ipcRenderer.on('sidebar', (_e, v) => cb(v)),
  onAssistant: (cb) => ipcRenderer.on('assistant', (_e, v) => cb(v)),
  onFocusAddress: (cb) => ipcRenderer.on('focus-address', () => cb()),
  onAdblockCount: (cb) => ipcRenderer.on('adblock-count', (_e, n) => cb(n)),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', () => cb()),
  onAIStatus: (cb) => ipcRenderer.on('ai-status', (_e, s) => cb(s)),
  onAIChunk: (cb) => ipcRenderer.on('ai-chunk', (_e, c) => cb(c)),
  onAIDone: (cb) => ipcRenderer.on('ai-done', () => cb()),
  onAICleared: (cb) => ipcRenderer.on('ai-cleared', () => cb()),
});
